<template>
  <section class="banner_part bg-gray-900">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-7">
          <div class="banner_text">
            <div class="banner_text_iner">
              <h1>RCL2 - Online Link Sharing</h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                sed do eiusmod tempor incididunt ut labore et dolore magna
                aliqua. Ut enim ad minim veniam.</p>
              <a href="#" class="btn_2 banner_btn_1"><span class="fa-brands fa-chrome"></span> Chrome Extension </a>
              <a href="#" class="btn_2 banner_btn_2"><span class="fa-brands fa-github"></span> Github </a>
            </div>
          </div>
        </div>
        <div class="col-lg-5">
          <div class="banner_img d-none d-lg-block">
            <img src="banner_img.png.png" alt="">
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
export default {
  name: 'App'
}
</script>

<style>
/* File generated by shrinker.ch - DateTime: 2023-10-09, 21:36:27 */
@media screen {

  *,
  ::after,
  ::before {
    box-sizing: border-box
  }

  section {
    display: block
  }

  body {
    margin: 0;
    height:100vh;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #212529;
    text-align: left;
  }

  h1 {
    margin-top: 0;
    margin-bottom: .5rem
  }

  p {
    margin-top: 0;
    margin-bottom: 1rem
  }

  a {
    color: #007bff;
    text-decoration: none;
    background-color: transparent
  }

  a:hover {
    color: #0056b3;
    text-decoration: underline
  }

  img {
    vertical-align: middle;
    border-style: none
  }

  h1 {
    margin-bottom: .5rem;
    font-weight: 500;
    line-height: 1.2
  }

  h1 {
    font-size: 2.5rem
  }

  .container {
    width: 100%;
    padding-right: 15px;
    padding-left: 15px;
    margin-right: auto;
    margin-left: auto
  }

  @media(min-width:576px) {
    .container {
      max-width: 540px
    }
  }

  @media(min-width:768px) {
    .container {
      max-width: 720px
    }
  }

  @media(min-width:992px) {
    .container {
      max-width: 960px
    }
  }

  @media(min-width:1200px) {
    .container {
      max-width: 1140px
    }
  }

  .row {
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    margin-right: -15px;
    margin-left: -15px
  }

  .col-lg-5,
  .col-lg-7 {
    position: relative;
    width: 100%;
    padding-right: 15px;
    padding-left: 15px
  }

  @media(min-width:992px) {
    .col-lg-5 {
      -ms-flex: 0 0 41.666667%;
      flex: 0 0 41.666667%;
      max-width: 41.666667%
    }

    .col-lg-7 {
      -ms-flex: 0 0 58.333333%;
      flex: 0 0 58.333333%;
      max-width: 58.333333%
    }
  }

  .d-none {
    display: none !important
  }

  @media(min-width:992px) {
    .d-lg-block {
      display: block !important
    }
  }

  .align-items-center {
    -ms-flex-align: center !important;
    align-items: center !important
  }

  @media print {

    *,
    ::after,
    ::before {
      text-shadow: none !important;
      box-shadow: none !important
    }

    a:not(.btn) {
      text-decoration: underline
    }

    img {
      page-break-inside: avoid
    }

    p {
      orphans: 3;
      widows: 3
    }

    body {
      min-width: 992px !important
    }

    .container {
      min-width: 992px !important
    }
  }

  .btn_2:hover {
    background-image: linear-gradient(to left, #00b4ff 0, #57ddff 51%, #00b4ff 100%)
  }

  .banner_part .banner_text .banner_btn_1:hover,
  .banner_part .banner_text .banner_btn_2:hover {
    background-image: linear-gradient(to left, #57ddff 0, #57ddff 51%, #57ddff 100%)
  }

  body {
    font-family: "Roboto", sans-serif;
    padding: 0;
    margin: 0;
    font-size: 14px
  }

  a {
    text-decoration: none;
    -webkit-transition: .5s;
    transition: .5s
  }

  a:hover {
    outline: 0;
    text-decoration: none
  }

  h1 {
    color: #1a1a1a;
    font-family: "Poppins", sans-serif
  }

  p {
    font-family: "Roboto", sans-serif;
    line-height: 2;
    font-size: 15px;
    margin-bottom: 0;
    color: #7f7f7f;
    font-weight: 300
  }

  img {
    max-width: 100%
  }

  a:focus {
    text-decoration: none;
    outline: 0;
    box-shadow: none;
    -webkit-transition: 1s;
    transition: 1s
  }

  @media only screen and (min-width:1200px) and (max-width:3640px) {
    .container {
      max-width: 1170px
    }
  }

  .btn_2 {
    display: inline-block;
    padding: 18.5px 40px;
    border-radius: 5px;
    background-color: #fff;
    font-size: 15px;
    font-family: "Poppins", sans-serif;
    font-weight: 500;
    color: #1a1a1a;
    -o-transition: all .4s ease-in-out;
    -webkit-transition: all .4s ease-in-out;
    transition: all .4s ease-in-out;
    text-transform: capitalize;
    border: 1px solid #8f9091;
    background-size: 200% auto
  }

  .btn_2:hover {
    color: #fff !important;
    border: 1px solid #0ab6ff;
    background-position: right center
  }

  @media(max-width:576px) {
    .btn_2 {
      padding: 10px 30px;
      margin-top: 20px
    }
  }

  @media only screen and (min-width:576px) and (max-width:767px) {
    .btn_2 {
      padding: 10px 30px;
      margin-top: 20px
    }
  }

  @media only screen and (min-width:768px) and (max-width:991px) {
    .btn_2 {
      padding: 10px 30px;
      margin-top: 25px
    }
  }

  .banner_part {
    position: relative;
    overflow: hidden;
    background-image: url('cool-background.svg');
    background-repeat: no-repeat;
    background-size: cover;
    background-position: center
  }

  .banner_part .banner_text {
    display: table;
    width: 100%;
    height: 1020px
  }

  .banner_part .banner_text .banner_text_iner {
    display: table-cell;
    vertical-align: middle
  }

  @media(max-width:991px) {
    .banner_part .banner_text {
      height: 650px
    }
  }

  @media only screen and (min-width:992px) and (max-width:1200px) {
    .banner_part .banner_text {
      height: 650px
    }
  }

  .banner_part .banner_text h1 {
    font-size: 55px;
    text-transform: capitalize;
    font-weight: 700;
    margin-bottom: 55px;
    line-height: 1.18;
    color: #fff
  }

  @media(max-width:576px) {
    .banner_part .banner_text h1 {
      font-size: 25px;
      margin-bottom: 15px;
      line-height: 1.3
    }
  }

  @media only screen and (min-width:576px) and (max-width:767px) {
    .banner_part .banner_text h1 {
      font-size: 30px;
      margin-bottom: 15px;
      line-height: 1.3
    }
  }

  @media only screen and (min-width:768px) and (max-width:991px) {
    .banner_part .banner_text h1 {
      font-size: 40px;
      margin-bottom: 15px;
      line-height: 1.3
    }
  }

  @media only screen and (min-width:992px) and (max-width:1200px) {
    .banner_part .banner_text h1 {
      font-size: 40px;
      margin-bottom: 15px;
      line-height: 1.4
    }
  }

  .banner_part .banner_text p {
    font-size: 15px;
    line-height: 1.8;
    font-family: "Poppins", sans-serif;
    color: #fff;
    margin-bottom: 57px;
    padding-right: 140px
  }

  @media(max-width:991px) {
    .banner_part .banner_text p {
      padding-right: 0;
      margin-bottom: 10px
    }
  }

  @media only screen and (min-width:992px) and (max-width:1200px) {
    .banner_part .banner_text p {
      padding-right: 0
    }
  }

  .banner_part .banner_text .banner_btn_1 {
    color: #0ab6ff;
    border: 0 solid transparent;
    margin-right: 28px
  }

  .banner_part .banner_text .banner_btn_1:hover {
    background-color: #0ab6ff !important;
    color: #fff
  }

  .banner_part .banner_text .banner_btn_2 {
    color: #fff;
    border: 1px solid #fff;
    background-color: transparent
  }

  .banner_part .banner_text .banner_btn_2:hover {
    background-color: #0ab6ff !important;
    color: #fff;
    border: 1px solid transparent
  }

  h1 {
    font-size: 36px
  }

  h1 {
    line-height: 1.2em
  }
}</style>